import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import '../styles/globals.css'
import { cn } from '@/lib/utils'
import { Sidebar } from '@/components/common/sidebar'
import { ThemeProvider } from './theme-provider'
import { PlayerProvider } from '@/providers/player'
import { PlayerController } from '@/components/player-controller'

const font = DM_Sans({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn('font-sans', font.variable)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Sidebar />
          <PlayerProvider>
            <div className="flex h-screen flex-col">
              <div className="flex-1">{children}</div>
              <PlayerController />
            </div>
          </PlayerProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
